from hands.royalflush import royalflush
from hands.straightflush import straightflush
from hands.fourofakind import fourofakind
from hands.fullhouse import fullhouse
from hands.flush import flush
from hands.straight import straight
from hands.threeofakind import threeofakind
from hands.twopair import twopair
from hands.onepair import onepair
from hands.highcard import highcard